/*
 ===========================================
 Filename: V1.0.2__create_tables_and_indexes.sql
 
# Copyright (c) 2025 Keona Gagnier
# This software is licensed under the MIT License, located in the root directory
# of this project (LICENSE file).
# ------------------------------------------------------------------------------
# Author(s): Keona Gagnier
# Date Created: Nov 28 2025
# Last Modified: December 12 2025
#
# Use of AI: 
# Gemini AI was used to help debug and improve the script. 
# All AI-generated suggestions were reviewed, verified, and modified by the author 
# before inclusion.
#
# Description:
# This creates the stocks table and the indexes on the stocks table.
  The table is made in the stock_user schema.
*/

CREATE TABLE stock_user.stocks (

    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    symbol VARCHAR2(10) NOT NULL,

    trade_date TIMESTAMP NOT NULL,

    open NUMBER(10,4),

    low NUMBER(10,4),

    high NUMBER(10,4),

    close NUMBER(10,4),

    volume NUMBER(19),

    CONSTRAINT stocks_symbol_date_uniq UNIQUE (symbol, trade_date)

)

TABLESPACE stocks_data;



CREATE INDEX stock_user.STOCKS_SYMBOL_IDX ON stock_user.stocks (symbol) TABLESPACE stocks_index;



CREATE INDEX stock_user.STOCKS_DATE_IDX ON stock_user.stocks (trade_date) TABLESPACE stocks_index;


